Lambda-School-Labs/student-art-collection-fe

- src/components/forms/Register.js
Basic form built. Will need information from API, testing, and styling to complete.
Initial
> skeleton user registration form

- .prettierrc.js
- src/index.js
- src/serviceWorker.js
Added serviceWorker in order to deploy on Netlify, it would not compile without it. I also added the prettier configuration file to match the backend configurations and taking into account jsx for the front-end.
Netlify serviceWorker build error
Added serviceWorker file and prettier file
> Prettier update file with settings and serviceWorker file add for Netlify deploy.

- src/components/forms/Login.js
- Built skeleton for the login form
- Waiting for the database information to add authentication  
- Still needs styling 
> login form started

- src/components/forms/Submission.js
Created submission form to allow the user to create a new art listing.
NA
Added new form.
> Created Submission form to upload art listing

- src/components/forms/Register.js
Merged the original branch too soon. Reverted it to get it out of Master. The code disappeared, so deleted the original register-form branch and the revert branch. 
> redo register-form branch

- package.json
- src/App.js
- src/components/forms/Login.js
- src/components/forms/Register.js
- src/components/images/images.js
- src/index.js
- yarn.lock
We can now pull and push to the database. 
- Manually tested with observers watching me
> Pull images from database

- src/App.js
- src/components/ImageMasonry.js
- src/components/index.js
- src/views/BrowseListings.js
Initial take on how users can browse artist's listings.
> Browse listings

- package.json
- public/index.html
- src/App.js
- src/components/forms/Login.js
- yarn.lock
Basic styling was implemented on the login form using Material-UI and Styled Components.
> Login form initial styling

- src/App.js
- src/components/ArtInfo.js
- src/components/ImageCarousel.js
- src/components/index.js
- src/views/SinglePage.js
- src/views/index.js
- yarn.lock
This where a user will be taken when they click on an image on the Browse page. Will have an image carousel/slider to display multiple images, information about the piece, and the contact form. As of now, it only displays a single image, and the contact form needs some styling.
> Single page

- src/App.js
- src/components/forms/Login.js
- src/components/forms/Register.js
Basic styling implemented on the register form using Material-UI and Styled Components.
> Register form initial styling

- src/components/forms/Login.js
- src/components/forms/Register.js
The login and register forms needed to be fixed to have the button within the form for them to be functional. Also added is the type 'required' on the login form inputs and a link to the register form from the bottom of the login component.
> Fixed issue on login and register forms plus minor updates

- src/components/GraphErrors.js
- src/components/GraphLoading.js
- src/components/ImageMasonry.js
- src/components/index.js
- src/styles/muiButtons.js
- src/styles/theme.js
- src/views/SinglePage.js
On components making queries or mutations, this will show a loading component (basic spinner) while loading, and an error component if there is an error (and allows users to go to the root route). I've added it to the Browse and Singles page.
> Errors loading

- src/App.js
- src/components/Navigation.js
- src/components/auth/Auth.js
- src/components/auth/PrivateRoute.js
- src/components/forms/Login.js
- src/components/forms/Register.js
This fixes an issue with the `PrivateRoute` component that kept it from rendering the component behind authentication when the user was logged in. The `PrivateRoute` was not waiting for the authentication to complete and rendered the `Redirect` component incorrectly.
I also now have the `Login` and `Register` components redirecting to `/dashboard` when they submit.
I also added a `Sign Out` button to the `Navigation` component.
Manual testing has been completed on all components to confirm functionality.
> Private Route Auth Fix and routing to dashboard

- src/App.js
- src/components/forms/Contact.js
- src/components/forms/Login.js
- src/components/tests/Contact.test.js
- yarn.lock
Adds a contact form where there was no contact form before!
-Manually tested on back-end and front-end
-Tested in Jest with React testing library and Apollo react testing
> Contact form frontend

- src/components/forms/Contact.js
- src/components/forms/Login.js
- src/components/forms/Register.js
Form placeholders needed to be added in to the contact, login, and register forms for testing to work.
> Added placeholders on forms

- src/components/forms/Contact.js
Had to refactor some code and update the Contact form.
-Reran test environment
> Updated contact form, all fields clear after sending the message

- src/components/forms/Submission.js
Basic MaterialUI styling added to the submission form.
> Initial styling on the submission form

- public/_redirects
Making it so you can manually go type in the route you wish to go to on our site
React router issue
-Manually tested
> React router update

- src/App.js
- src/components/Dashboard.js
- src/components/EditConsole.js
- src/components/index.js
- src/views/AdminSingleView.js
- src/views/index.js
Single view of an artwork for admins with delete functionality, and routing to the edit form.
> Admin single view

- src/components/Dashboard.js
Dashboard Form
Styling to better suit the page and added a routed button for adding a new listing.
> Dashboard form

- src/components/CategorySelection.js
margin added to category dropdown
> Margin added to category dropdown

- src/components/Dashboard.js
- src/components/forms/EditForm.js
- src/components/forms/Submission.js
- src/views/AdminSingleView.js
Fetches queries after PUT/POST are sent to the database
-Manually
> Now loading all items on the dashboard, queries refetch properly!

- src/components/forms/Login.js
- src/components/forms/Register.js
- src/views/AdminSingleView.js
Ensured that deleting works and that the routes are updated.
-Manually
> Deleting works, everything routes as it should

- src/components/Dashboard.js
Initial styling to the dashboard component updated
> Dashboard styling updates

- src/App.js
- src/components/Dashboard.js
- src/components/forms/Submission.js
Avoiding the use of the firebase uid in the newArt mutation. Now uses the primary key of the schools database.
> One more graphql debug

- src/index.js
- yarn.lock
Co-authored-by: Dave Inden <davidinden@gmail.com>
Co-authored-by: Ian Schwartz <ian.schwartz23@gmail.com>
Co-authored-by: Grissobel Payonk <grissobel.castro@gmail.com>
Co-authored-by: Jason Loomis <jason@jrloomis.com>
Co-authored-by: Ami Scott <amiezrascott@gmail.com>
Doesn't
> Logging errors from apollo for graphql

- src/views/AdminSingleView.js
Delete function should now properly work.
-Manually
> Fixing delete function

- src/components/forms/Contact.js
- src/components/forms/EditForm.js
- src/components/forms/Login.js
- src/components/forms/Register.js
Updated button colors from primary/blue to #3CBBB1
> Button color changes

- src/components/Navigation.js
Changed the navbar so that a logged in user can see the browse button.
> logged in user can see browse button in navbar

- src/components/forms/EditForm.js
> Form formatting

- package.json
- src/App.js
- src/index.js
- src/styles/muiAppContainer.js
- yarn.lock
Normalize.css has been added as a dependency and imported in index.js. Also a MaterialUI container has been created with baseline styling to wrap our app with.
CSS reset
--- This change may effect how content is currently displayed  ---
> App styling

- src/components/Dashboard.js
- src/components/ImageMasonry.js
- src/views/BrowseListings.js
The browse listings page was updated with new styling including the addition of a header and changes to the cards to make them consistent with the dashboard. A couple minor sizing and style tweaks were made to the dashboard as well.
> Browse listings updates

- src/index.js
- src/views/AdminSingleView.js
- src/views/SinglePage.js
Co-authored-by: Dave Inden <davidinden@gmail.com>
Co-authored-by: Ian Schwartz <ian.schwartz23@gmail.com>
Co-authored-by: Grissobel Payonk <grissobel.castro@gmail.com>
Co-authored-by: Jason Loomis <jason@jrloomis.com>
Co-authored-by: Ami Scott <amiezrascott@gmail.com>
Everything broke, now it isn't broken.
- Manually
> Fixed editing bug where everything broke and crashed all the time

- src/App.js
- src/components/Dashboard.js
- src/components/ImageMasonry.js
- src/components/Navigation.js
- src/components/forms/Login.js
- src/components/forms/Register.js
- src/styles/muiForms.js
- src/views/MainPage.js
Styling updates across the app including tweaks to the main page, some added media queries, and the appbar made sticky to prevent content from flowing under it.
> Styling updates 

- src/components/Dashboard.js
- src/components/ImageMasonry.js
- src/components/forms/EditForm.js
- src/components/forms/Login.js
- src/components/forms/Register.js
- src/components/forms/Submission.js
- src/styles/muiForms.js
- src/views/AdminSingleView.js
- src/views/MainPage.js
- src/views/SinglePage.js
The header was slimmed down so it doesn't take up as much of the page on smaller screens. Margin and font sizes were also lessened. Background color added to login and register forms and also some media query adjustments were made.
> Styling updates

- src/components/forms/Login.js
> breakpoint for login adjusted

- README.md
I commented out the placeholder for Content Licensing for later use
Updated documentation links at bottom to other projects
Updated link to the deployed production project to use the domain name we purchased
Updated section on testing to note where to find the command
Fixed Jason's picture to pull from their GitHub profile. It was a broken image before.
I also updated one of the links for Jason to go to their correct GitHub profile/
Manually reviewed the documentation.
> Fixes and updates to README

- src/components/Dashboard.js
- src/components/ImageMasonry.js
- src/components/Quotes.js
- src/styles/theme.js
Font size increased on header, color added, margin
> font size increased on header, color added, margin

- src/components/Dashboard.js
- src/components/Quotes.js
> dashboard and browse fixed

- src/components/forms/Contact.js
Co-authored-by: Dave Inden <davidinden@gmail.com> 
Co-authored-by: Ian Schwartz <ian.schwartz23@gmail.com> 
Co-authored-by: Grissobel Payonk <grissobel.castro@gmail.com> 
Co-authored-by: Jason Loomis <jason@jrloomis.com> 
Co-authored-by: Ami Scott <amiezrascott@gmail.com>
- Manually
> Fixed the email function probably

- src/components/about/Team.css
- src/components/about/Team.js
About Page
Added media responsiveness up to 2000 and close button function.
> Team about page

- src/views/SearchResults.js
We now have a message that shows up when no results are found!
- Manually
> Complete! Added a message when results are not found!

- src/components/CategorySelection.js
- src/components/GraphErrors.js
- src/styles/muiButtons.js
- src/views/AdminSingleView.js
- src/views/BrowseListings.js
- src/views/SinglePage.js
Fix
Back button on single views, or when error wasn't displaying the arrow.
> Back button fix

- src/App.js
- src/components/Dashboard.js
- src/components/NavbarAuth.js
- src/components/NavbarNonAuth.js
- src/components/Navigation.js
- src/components/NotificationModal.js
- src/components/forms/EditProfile.js
- src/components/index.js
- src/context/SchoolContext.js
- src/views/UserProfile.js
- src/views/index.js
A basic user profile page. Users can change various information.
> User profile

- src/components/ArtInfo.js
- src/components/NavbarAuth.js
- src/components/about/Team.css
- src/components/about/Team.js
- src/components/forms/EditForm.js
- src/components/forms/Submission.js
- src/styles/theme.js
- src/views/SearchResults.js
Improved mobile responsiveness on submit and edit forms, art info cards styling, about page typography, search results back button
> Form responsiveness and styling updates

- src/components/FileUpload.js
- src/components/forms/Submission.js
Allows for an array of images to be uploaded to Cloudinairy/our database
-Manually
> Upload image fix

- src/components/ImageCarousel.js
doesn't use carousel with single image
> doesn't use carousel with single image

- src/components/about/Team.js
> fixing broken links

- src/components/ImageCarousel.js
Co-authored-by: Ami Scott <amiezrascott@gmail.com>
Co-authored-by: Jason Loomis <jason@jrloomis.com>
Co-authored-by: Grissobel Payonk <grissobel.castro@gmail.com>
Co-authored-by: dAVE Inden <davidinden@gmail.com>
Co-authored-by: <mack.webb37@gmail.com>
> fixes for image height, carousel, media queries added

- src/components/Dashboard.js
- src/components/NavbarAuth.js
- src/components/forms/EditProfile.js
- src/views/UserProfile.js
Co-authored-by: Dave Inden <davidinden@gmail.com>
Co-authored-by: Ian Schwartz <ian.schwartz23@gmail.com>
Co-authored-by: Grissobel Payonk <grissobel.castro@gmail.com>
Co-authored-by: Jason Loomis <jason@jrloomis.com>
Issue of update not working properly
- Manually
> Fixed issue with profile update not working properly.

- src/components/ImageCarousel.js
- src/components/about/Team.css
Image too small on single art view - medium screen size. About page margin adjustment.
> single art breakpoint sizing fixed, about page margin adjustment
